server:
  port: 8089

spring:
  r2dbc:
    url: r2dbc:postgres://localhost:5432/postgres
    username: postgres
    password: root
    pool:
      enabled: true
      initial-size: 1
      max-size: 1

logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG